alias dkr='docker $*'
alias dco='docker-compose $*'
alias dcup='docker-compose up'
alias dcdown='docker-compose down'
alias dclogs='docker-compose logs --tail="all"'
alias dcforce='docker-compose up --build --force-recreate'
alias dcm='docker-machine'
